### ISSUE TITLE
Swagger documentation does not represent object for relations

### ISSUE THREAD

**Issue by soullivaneuh** [api-platform/core#2964]
With the following entities:

```php
/**
 * @ORM\Table(indexes={
 *     @ORM\Index(name="server_name_idx", columns={"name"})
 * })
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ServerRepository")
 * @UniqueEntity({"name", "hostedDomain"})
 * @ApiResource(
 *     collectionOperations={"get", "post"},
 *     itemOperations={
 *         "get",
 *         "put",
 *         "delete",
 *         "puppet" = {
 *             "method" = "GET",
 *             "path" = "/servers/{id}/puppet",
 *             "controller" = ServerPuppet::class,
 *             "access_control" = "is_granted('ROLE_ADMIN')",
 *             "swagger_context" = {
 *                 "summary" = "Retrieves Puppet configuration of the given server."
 *             }
 *         }
 *     }
 * )
 * @OwnerAware
 */
class Server implements OwnableInterface
{
    /**
     * @var IpV4[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\IpV4", mappedBy="server")
     *
     * @Groups({"gets", "post:admin"})
     */
    private $ipV4s;

    /**
     * Returns public system IP. Null if not exists.
     *
     * @Groups("gets")
     */
    public function getPublicSystemIp(): ?IpV4
    {
        foreach ($this->ipV4s as $ip) {
            if ($ip->getSystemIp() && IpV4::NETWORK_PUBLIC === $ip->getNetwork()) {
                return $ip;
            }
        }

        return null;
    }
}

/**
 * @ORM\Table(indexes={
 *     @ORM\Index(name="ip_v4_network_idx", columns={"network"})
 * })
 * @ORM\Entity(repositoryClass="AppBundle\Repository\IpV4Repository")
 * @DoctrineAssert\UniqueEntity({"ip"})
 * @ORM\HasLifecycleCallbacks
 * @ApiResource(
 *     collectionOperations={"get"},
 *     itemOperations={"get"}
 * )
 * @OwnerAware(fields={"server"})
 */
class IpV4 implements OwnableInterface
{
    public const NETWORK_PUBLIC = 'public';
    public const NETWORK_PRIVATE = 'private';

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Groups("gets:admin")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=15, unique=true)
     * @Assert\NotBlank
     * @Assert\Ip(version="4")
     * @Groups("gets")
     * @ApiFilter(SearchFilter::class, strategy="partial")
     */
    private $ip;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=10)
     * @Groups("gets")
     */
    private $network;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     * @Groups("gets")
     */
    private $systemIp = false;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $pingable = false;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $pingTestedAt;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=32, nullable=true)
     * @Assert\Length(max=32)
     */
    private $alias;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $addedAt;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $modifiedAt;

    /**
     * @var IpGroup|null
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\IpGroup", inversedBy="ipV4s")
     * @ORM\JoinColumn(referencedColumnName="id", nullable=true)
     * @Groups("gets")
     */
    private $group;

    /**
     * @var Server|null
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Server", inversedBy="ipV4s")
     * @ORM\JoinColumn(referencedColumnName="id", nullable=true, onDelete="SET NULL")
     */
    private $server;

    // ...
}
```

If I dump the generated server definition:

```php
$docs = $this->normalizer->normalize($object, $format, $context);
dump($docs['definitions']['Server']);
```

I got `string` for the IP value:

```
  storage: array:4 [▼
    "type" => "object"
    "description" => ""
    "properties" => array:59 [▼
      "name_with_my_s_q_l_compliant" => ArrayObject {#10092 ▶}
      "name_for_select" => ArrayObject {#10096 ▶}
      "name_with_owners" => ArrayObject {#10084 ▶}
      "public_system_ip" => ArrayObject {#10073 ▼
        flag::STD_PROP_LIST: false
        flag::ARRAY_AS_PROPS: false
        iteratorClass: "ArrayIterator"
        storage: array:3 [▼
          "readOnly" => true
          "description" => "Returns public system IP. Null if not exists."
          "type" => "string"
        ]
      }
```

Instead, I should have a representation of what will be return by the API (id, ip, network...).

Maybe it's a misconfiguration, but it does not look normal to me.

Regards

**Comment by slawekp** [comment]
It seems that I'm dealing with the same issue. @soullivaneuh were you able to find out if it was a misconfiguration in your case?

**Comment by dunglas** [comment]
It should be fixed in master. Would you mind to give a try?

**Comment by soullivaneuh** [comment]
@dunglas May you please specify where this is fixed?

I recently updated the project to v2.5.3 without any change.

**Comment by Byidi** [comment]
I have try on a new project and this still seems no fix. 

https://github.com/Byidi/api-platform-parameter,

and the doc still present all the return as string.

![image](https://user-images.githubusercontent.com/8182848/89737390-d4d2d280-da70-11ea-8a30-679acc915bbb.png)

![image](https://user-images.githubusercontent.com/8182848/89737394-e0be9480-da70-11ea-953a-7481ce932afb.png)
