### ISSUE TITLE
Subresource customisation DX is poor and confusing.

### ISSUE THREAD

**Issue by bendavies** [api-platform/core#3458]
**Description**  
The need arose in my project to start using sub resources.
Here's where I had trouble.
I needed to:
1. specify a custom path for the sub resource
1. specify custom serialization groups in the normalization context.

Great, I thought, both of these features are supported: [1](https://api-platform.com/docs/core/subresources/#using-custom-paths), [2](https://api-platform.com/docs/core/subresources/#using-serialization-groups)

However, after failing to get these working together for about 30 minutes, I realized I had read the docs incorrectly.
If we take the example from the docs, this is what I was trying:

```php
<?php
// api/src/Entity/Question.php

/**
 * ...
 * @ApiResource(
 *      subresourceOperations={
 *          "api_questions_answer_get_subresource"={
 *              "method"="GET",
 *              "path"="/questions/{id}/all-answers",
  *             "normalization_context"={"groups"={"foobar"}}
 *          },
 *      },
 * )
 */
class Question
{
    /**
     * @ORM\OneToOne(targetEntity="Answer", inversedBy="question")
     * @ORM\JoinColumn(referencedColumnName="id", unique=true)
     * @ApiSubresource
     */
    public $answer;
}
```

Looks fine right?
Well actually it's wrong.

Two issues,
1. The `subresourceOperations` name is wrong. [PR Raised.](https://github.com/api-platform/docs/pull/1071) ~~`~~api_questions_`~~`answer_get_subresource`. 
1. To to override the normalization_context, the `subresourceOperations` options must actually be on the `Answer` Entity, not `Question`. This IS actually in the docs, but i missed it because it's not really obvious or explained.

So the correct config is this:

```php
<?php
// api/src/Entity/Question.php

/**
 * ...
 * @ApiResource(
 *      subresourceOperations={
 *          "answer_get_subresource"={
 *              "method"="GET",
 *              "path"="/questions/{id}/all-answers"
 *          },
 *      },
 * )
 */
class Question
{
    /**
     * @ORM\OneToOne(targetEntity="Answer", inversedBy="question")
     * @ORM\JoinColumn(referencedColumnName="id", unique=true)
     * @ApiSubresource
     */
    public $answer;
}
```

```php
<?php
// api/src/Entity/Answer.php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ApiResource(subresourceOperations={
 *     "api_questions_answer_get_subresource"={
 *         "normalization_context"={"groups"={"foobar"}}
 *     }
 * })
 */
class Answer
{
}
```

This works, but here is the kicker:

For this to work the operation name must be
1. On `Question`: `answer_get_subresource`. This is the `operation_name`.
2. On `Answer`: `api_questions_answer_get_subresource`. This is the `route_name`.

This took me far too long to work out and seems crazy from a DX point of view.
I'm not sure if this is a bug or a design constraint. Can it be improved?

The optimum for DX in my opinion would be if the the config was done as my first example, which doesn't work, with it all sitting in the `Question` Entity.

Thanks

**Comment by potasiyam** [comment]
Thanks for explaining your findings. I was so confused with it. Finally the custom path worked but serialisation groups for subresources still doesn't work for me. I tried with v2.5.9.

**Comment by bendavies** [comment]
@soyuka is this being addressed with the subresource refactorings taking place that i think i read about?

**Comment by soyuka** [comment]
Definitely @bendavies, we need to come to a consensus on https://github.com/api-platform/core/blob/0f345716d4917b8c5a0071f46cbd9b059ca7bf2f/docs/adr/0002-resource-definition.md (https://github.com/api-platform/core/pull/3915 - we need a few more meetings with the core team) then I'll implement it. Basically there won't be any `@ApiSubresource` in 3.x and so-known "subresources" will just be a new Resource declaration with a complex path.

Your input is very welcome on #3915 btw.

**Comment by stiffroy** [comment]
> Thanks for explaining your findings. I was so confused with it. Finally the custom path worked but serialisation groups for subresources still doesn't work for me. I tried with v2.5.9.

@potasiyam Could you solve it with the `serialization groups`? I am on version 2.6.3 of ApiPlatform but still have the same problem.

**Comment by stiffroy** [comment]
I have finally solved the `serialization groups`. It was a bit tricky and had to try a lot of different things. I solved it finally in the bellow process: (Please refer to the main example of this post if needed).

```php

<?php
// api/src/Entity/Question.php

/**
 * ...
 * @ApiResource(
 *      subresourceOperations={
 *          "answer_get_subresource"={
 *              "method"="GET",
 *              "path"="/questions/{id}/all-answers"
 *          },
 *      },
 * )
 */
class Question
{
    /**
     * @ORM\OneToOne(targetEntity="Answer", inversedBy="question")
     * @ORM\JoinColumn(referencedColumnName="id", unique=true)
     * @ApiSubresource
     */
    public $answer;
}
```

and the `Answer` entity as 

```php
<?php
// api/src/Entity/Answer.php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ApiResource(
 *      collectionOperations={
 *          "api_questions_answer_get_subresource"={
 *              "normalization_context"={"groups"={"foobar"}}
 *          }
 *      }
 * )
 */
class Answer
{
}

```

Note here that in the `Answer` entity, I had to put the route name based normalization information under the `collectionOperations` and **NOT** the `subresourceOperations`

**Comment by bendavies** [comment]
@stiffroy yes, i detail exactly that in my OP, don't I?

**Comment by bendavies** [comment]
@stiffroy no idea, i have exactly as per my OP, i.e. in `subresourceOperations` in a app on v2.6.3, and it works fine.

**Comment by stiffroy** [comment]
@bendavies Strange... I am also using version 2.6.3 but cannot make it work. I am not sure if this is because I am using DTOs. When ever I define the `subresourceOperation` on my `TargetEntity` Class, it gives me an error on the OpenAPI documentation page whenever I click on the endpoint to test it.

```php
{
  "hydra:member": [
    null
  ],
  "hydra:totalItems": 0,
  "hydra:view": {
    "@id": "string",
    "@type": "string",
    "hydra:first": "string",
    "hydra:last": "string",
    "hydra:next": "string"
  },
  "hydra:search": {
    "@type": "string",
    "hydra:template": "string",
    "hydra:variableRepresentation": "string",
    "hydra:mapping": [
      {
        "@type": "string",
        "variable": "string",
        "property": "string",
        "required": true
      }
    ]
  }
}
```
