### ISSUE TITLE
[v2.7] Missing classes and a method visiblity change after update

### ISSUE THREAD

**Issue by darthf1** [api-platform/core#4955]
Hi!

Great job on the new releases! :D

When upgrading v2.6.8 to v2.7.0 I get a few errors related to missing or changed classes, and visibility changes on methods.

Below was reported originally:
```
Cannot autowire service "App\MyService": argument "$factory" of method "__construct()" references interface "ApiPlatform\Core\Bridge\Elasticsearch\Metadata\Document\Factory\DocumentMetadataFactoryInterface" but no such service exists. Did you create a class that implements this interface?                       
```

![image](https://user-images.githubusercontent.com/17253332/190453945-240000b8-a97b-4e0f-ad0f-15a01f35204b.png)

I also noticed another class missing:

![image](https://user-images.githubusercontent.com/17253332/190454180-793e1bef-5078-46d5-8286-7c6e4c5daee0.png)

New errors reported by PHPStan:
- Call to private method `getNestedFieldPath()` of class `ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Filter\AbstractFilter`.
- Parameter `#2` $propertyNameCollectionFactory of class Infrastructure\Shared\ApiPlatform\DataProvider\Extension\CompositeAggregationExtension constructor expects `ApiPlatform\Metadata\Property\Factory\PropertyNameCollectionFactoryInterface`, `ApiPlatform\Metadata\Property\Factory\CachedPropertyNameCollectionFactory` given.
- Parameter `#4` $resourceClassResolver of class Infrastructure\Shared\ApiPlatform\DataProvider\Extension\CompositeAggregationExtension constructor expects `ApiPlatform\Api\ResourceClassResolverInterface`, `ApiPlatform\Api\ResourceClassResolver` given.
- Class `ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Extension\AbstractFilterExtension` not found in file  
     /home/www/app/src/Infrastructure/Shared/ApiPlatform/DataProvider/Extension/SearchFilterExtension.php (more details in Infection section below)

New errors reported by my PHPUnit suite:
- Error: Class `ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Extension\ConstantScoreFilterExtension` not found

Another one by Infection:
```
Generating code coverage report in PHPUnit XML format ... The autoloader expected class `ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Extension\AbstractFilterExtension` to be defined in file "/builds/1/xxx/api/vendor/composer/../api-platform/core/src/Core/Bridge/Elasticsearch/DataProvider/Extension/AbstractFilterExtension.php". The file was found but the class was not in it, the class name or namespace probably has a typo. 
```

**Comment by babeuloula** [comment]
Hello,

The namespaces have changed. Use this : 
- ApiPlatform\Elasticsearch\Metadata\Document\Factory\DocumentMetadataFactoryInterface
- ApiPlatform\Serializer\SerializerContextBuilderInterface

**Comment by dunglas** [comment]
Anyway, this should work in 2.7. We'll try to fix that as soon as possible!

**Comment by darthf1** [comment]
I added additional reported phpstan errors in the first post :)

**Comment by darthf1** [comment]
Thanks for merging the fix @soyuka :D

Can you reopen since there's a few more items in this ticket? Or do you want a new ticket per issue?

**Comment by walva** [comment]
@darthf1 I will deal with DocumentMetadataFactoryInterface and SerializerContextBuilderInterface. First one was already addressed, and I'll work on the second one. If you find more missing classes, please let us know. I **might** try to detect them by myself.

**Comment by walva** [comment]
@darthf1 I solve the issue 
`Cannot autowire service "App\MyService": argument "$factory" of method "__construct()" references interface "ApiPlatform\Core\Bridge\Elasticsearch\Metadata\Document\Factory\DocumentMetadataFactoryInterface" but no such service exists. Did you create a class that implements this interface?                       
`
I don't mean to address the other issues (eg: phpstan errors). Could you check if you still have the issue ?

**Comment by darthf1** [comment]
> @darthf1 I solve the issue 
> `Cannot autowire service "App\MyService": argument "$factory" of method "__construct()" references interface "ApiPlatform\Core\Bridge\Elasticsearch\Metadata\Document\Factory\DocumentMetadataFactoryInterface" but no such service exists. Did you create a class that implements this interface?                       
> `
> I don't mean to address the other issues (eg: phpstan errors). Could you check if you still have the issue ?

Great, thank you!

Yes the other errors still exist, there's also missing classes in the other listed issues.

**Comment by soyuka** [comment]
Missing classes are aliased, it's only your IDE right? Also we diff'd service declarations and it looks okay.

**Comment by darthf1** [comment]
The error thrown in my test suite is not IDE related; I created https://github.com/api-platform/core/issues/5005.

**Comment by rendler-denis** [comment]
Having the same issue and switching to the new interfaces and classes is way longer than we have time right now.
I also found this:
![image](https://user-images.githubusercontent.com/1212958/191957220-cd63e23c-03e2-4516-931f-52c340762925.png)

I see two issues with this:
1) the new class is `final` and thus cannot be extended
2) how should the class be made available since the condition of `false` will never allow PHP to execute that code?

Any help is appreciated. Thanks
