### ISSUE TITLE
Unable to generate an IRI When serializing nested relationship

### ISSUE THREAD

**Issue by nsetyo** [api-platform/core#5073]
**API Platform version(s) affected**: 3.0.x

**Description**  
Given I have 4 Entity, Greeting, Organization, Address, and Country

Greeting belongsTo Organization, Organization hasMany Address, Address belongsTo Country

```
public function testSerializeGreeting(): void
    {
        $serializer = $this->getContainer()->get(SerializerInterface::class);
        $em = $this->getContainer()->get(EntityManagerInterface::class);

        $country = (new Country)->setCode('US');
        $em?->persist($country);

        $org = new Organization;
        $org->addAddress((new Address)->setCountry($country));
        $em?->persist($org);

        $greeting = (new Greeting)
            ->setName('Kévin')
            ->setOrg($org);

        $em?->persist($greeting);
        $em?->flush();

        $serialized = $serializer?->serialize($greeting, 'json');

        $this->assertIsString($serialized);
    }
 ```
 
 ```
 1) App\Tests\Api\GreetingsTest::testSerializeGreeting
ApiPlatform\Exception\InvalidArgumentException: Unable to generate an IRI for the item of type "App\Entity\Country"

/srv/app/vendor/api-platform/core/src/Symfony/Routing/IriConverter.php:152
/srv/app/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php:120
```

**How to reproduce**  
run phpunit on https://github.com/nsetyo/api-platform3-serializedbug

**Possible Solution**  

**Additional Context**  
Likely this is happened because when serializing Country the $operation class is Organization

**Comment by ihmels** [comment]
Your issue should be resolved if you make `Address` also an ApiResource. You can omit the route from the documentation and have it return a 404 when you add the `#[NotExposed]` attribute.

```
Greeting [ApiResource]
    -> Organization [ApiResource]
        -> Address
            -> Country [ApiResource]
```

For JSON-LD format it works without making `Address` a resource. I think this is because of the following:

https://github.com/api-platform/core/blob/1a3ae348dfd35d6d4117a7fcecaf1ecd1fe1e4ea/src/JsonLd/Serializer/ItemNormalizer.php#L92-L95

**Comment by nsetyo** [comment]
> Your issue should be resolved if you make `Address` also an ApiResource. You can omit the route from the documentation and have it return a 404 when you add the `#[NotExposed]` attribute.
> 
> ```
> Greeting [ApiResource]
>     -> Organization [ApiResource]
>         -> Address
>             -> Country [ApiResource]
> ```
> 
> For JSON-LD format it works without making `Address` a resource. I think this is because of the following:
> 
> https://github.com/api-platform/core/blob/1a3ae348dfd35d6d4117a7fcecaf1ecd1fe1e4ea/src/JsonLd/Serializer/ItemNormalizer.php#L92-L95

Indeed. It solved the issue, the thing is when I make Address ApiResource api-platform wont allows me to insert nested document

`"Nested documents for attribute \u0022addresses\u0022 are not allowed. Use IRIs instead."`

**Comment by nsetyo** [comment]
@soyuka I'm still experiencing this after update, what can I do to help fix this? I'm not familiar with Behat
