### ISSUE TITLE
ElasticSearch filter documentation incorrect

### ISSUE THREAD

**Issue by BernardA** [api-platform/core#5477]
**API Platform version(s) affected**: 3.1.3

**Description**  

On the example shown on the [documentation](https://api-platform.com/docs/core/filters/) the `RequestBodySearchCollectionExtensionInterface` uses the signature below:

            public function applyToCollection(array $requestBody, string $resourceClass, ?string $operationName = null, array $context = []): array

It seems that the `$operationName` was  replaced by `Operation`,  from `ApiPlatform\Metadata\Operation`.:

          public function applyToCollection(array $requestBody, string $resourceClass, ?Operation $operation = null, array $context = []): array;

Additionally, when attempting to create a custom filter with above, it will require the implementation of `FilterInterface`  and its `getDescription()` method. 

In my specific case, I could not find a good use of the `getDescription()` method. 

So, it might be good idea to add that to the docs, possibly with an example that actually uses `FilterInterface`. 

       use ApiPlatform\Elasticsearch\Extension\RequestBodySearchCollectionExtensionInterface;
       use ApiPlatform\Metadata\Operation;
       use ApiPlatform\Api\FilterInterface;

        class CustomMatchFilter implements RequestBodySearchCollectionExtensionInterface, FilterInterface

        ....
       public function getDescription(string $resourceClass): array
    {
        return [];
    }

**How to reproduce**  

**Possible Solution**  

**Additional Context**

**Comment by dannyvw** [comment]
Operation signature is fixed in https://github.com/api-platform/docs/pull/1735

**Comment by BernardA** [comment]
Thanks @dannyvw . That looks good, but I still have a couple of points from my recent experience creating a custom filter with the current documentation. 

First, and I stress that I am not an ES expert, I am not sure how the  ConstantScore rhymes with setting priorities to each field in a query. 

We had this query that was done outside API-Platform:


         $params = [
            'index' => 'my_index',
            'body'  => [
                'query' => [
                    'multi_match' => [
                        'query' => $critere,
                        'fields' => [
                            "raison_sociale^4",
                            "siret^3",
                            "siren^2",
                            "libelle_voie_etablissement",
                        ]
                    ]
                ]
            ]
        ];

I have created the following custom filter to handle that within API-Platform: 

        class MultiMatchFilter implements RequestBodySearchCollectionExtensionInterface, FilterInterface
    {
      public function __construct(private readonly ?array $args = null) {}

     public function applyToCollection(array $requestBody, string $resourceClass, ?Operation $operation = null, array $context = []): array
     {
        if (
            !isset($context['filters']['all']) 
            || !isset($this->args) 
            || isset($requestBody['query'])
            || $this->args['class'] !== $resourceClass) return $requestBody;

        unset($requestBody['sort']);

        $requestBody['query'] = [];
        $fields = [];
        foreach ($this->args['props'] as $prop) {
            $fields[] = $prop;
        }
        $query = [
            'query' => $context['filters']['all'],
            'fields' => $fields,
        ];
        
        $requestBody['query']['multi_match'] = $query;
        return $requestBody;
    }

    // only to satisfy requirement of implementing method from FilterInterface
    public function getDescription(string $resourceClass): array
    {
        return [];
    }

    }

Which was used like below in an instance of a Model class. Other Model classes use the same filter for `multi-match` query
on their specific fields.


       ApiFilter(
        MultiMatchFilter::class, 
        arguments: [
            'args' => [
                'class' => self::class,
                'props' => [
                            'raison_sociale_deduite^4',
                            'siret^3',
                            'siren^2',
                            'libelle_voie_etablissement',
               ]
              ]]);

The issue I had here - as the API-Platform code make several passes - was making sure that the desired query was not overwritten and I found no other way than checking if the query was not already set ( `isset($requestBody['query']`) and that 
the filter in question was the one coming from the current class ( `'class' => self::class`);

Then I had to override the default query to write my own, so as to correspond to the existing one. I am not saying that the existing query is perfect, I just had to stick to it, for now at least.

So, I am not sure the new `ConstantScoreFilterInterface` will address these issues, or may be I did not use it properly.
