### ISSUE TITLE
[ Question ] Add Method not working in many to many inversed side 

### ISSUE THREAD

**Issue by MajdiJ** [api-platform/core#572]
I have this many to many relationship between bus and driver .
In the bus entity I have : 
```
/**
     * @var ArrayCollection<Driver> The driver of this bus.
     * @ORM\ManyToMany(targetEntity="Driver", inversedBy="bus" , cascade={"persist"})
     * @ORM\JoinTable(name="bus_driver")
     * @ORM\JoinColumn(name="driver_id", referencedColumnName="id")
     * */
    private $driver;

    public function __construct() {
        $this->driver = new \Doctrine\Common\Collections\ArrayCollection();
    }


    public function addDriver($driver) {
        $this->driver[] = $driver;
        return $this;
    }
```
And this is the driver entity :
```

/**
     * @var ArrayCollection<Bus> The buses of this driver
     * @ORM\ManyToMany(targetEntity="Bus", mappedBy="driver")
     * @ORM\JoinTable(name="bus_driver")
     * @ORM\JoinColumn(name="bus_id", referencedColumnName="id")
     */
    private $bus;

public function __construct() {
        $this->bus = new \Doctrine\Common\Collections\ArrayCollection();
    }
 public function addBus($bus) {
        $this->bus[] = $bus;
        $bus->addDriver($this);
        return $this;
    }
```
My problem is that when I Post a bus with a driver the relation is persisted but not when I Post a driver whih a bus . It works only from the bus side. 
In the driver entity the addBus method is not even triggered in the post action (it is when I rename it to setBus)

**Comment by teohhanhui** [comment]
1. Your property naming is wrong according to convention. It should be `private $drivers;`.
2. Unfortunately the matching of plural properties to singular adder/remover is broken (see symfony/symfony#18166). It is already fixed in Symfony 3.2 (master). A workaround would be to use plural adder/remover (e.g. `addDrivers`).

**Comment by MajdiJ** [comment]
I tried that but still not working , the addSomthings method is not triggered by the post action .
The only thing that worked is :
```
public function setDrivers($driver) {
        $this->driver = $driver;
        return $this;
    }
```
This only works on the owning side (Bus) .

**Comment by MajdiJ** [comment]
The only working scenario was when I had : 

A setter for the drivers collection .
An addDriver Method .
A removeDriver Method. 

If I remove one of the pervious , addDriver/addBus won't even trigger at all .

**Comment by dunglas** [comment]
You can also install the 3.2@dev version of symfony/property-info in your composer.json.

It's what I plan to do in the standard edition during the meantime between the release of API Platform 3 and Synfony 3.2.

**Comment by Simperfit** [comment]
The [composer.json](https://github.com/api-platform/api-platform/blob/master/composer.json) has been updated with the new version of Api-Platform Standard Edition
