### ISSUE TITLE
Could not resolve argument "Symfony\Config\ApiPlatformConfig $config"

### ISSUE THREAD

**Issue by stephanvierkant** [api-platform/core#6670]
**API Platform version(s) affected**:
* api-platform/symfony 3.4.1
* api-platform/symfony  4.0.2
* api-platform/symfony  dev-main
 
**Description**  

I'm using PHP config in Symfony:

```
// config/packages/api_platform.php
use Symfony\Config\ApiPlatformConfig;

return static function (ApiPlatformConfig $config) : void {
    $config->mapping()
        ->paths([
         // ....
```

This used to work with `api-platform/core`, but it doesn't work after switching to `api-platform/symfony`:

>  Could not resolve argument "Symfony\Config\ApiPlatformConfig $config" for "/config/packages/api_platform.php" in /config/packages/api_platform.php (which is being imported from "/src/Kernel.php").

**Comment by dunglas** [comment]
Could you please try if it works when using core (it's still supported) instead of symfony (with same version). Thanks

**Comment by stephanvierkant** [comment]
Yes,core still works (3.4).

**Comment by stephanvierkant** [comment]
I tried api-platform/core v4.0.1 and I get this error:

> Resource "ApiPlatform\Symfony\Validator\Exception\ValidationException" not found.

**Comment by dunglas** [comment]
Could you try if https://github.com/api-platform/core/pull/6672 fixes the issue?

**Comment by dunglas** [comment]
I merged 3.4 into 4.0. This should be ok now.

**Comment by stephanvierkant** [comment]
Thanks! This solves my issue with api-platform/core v4, but it doesn't solve the issue with `api-platform/symfony`

**Comment by dunglas** [comment]
Thanks for the report.

You still have " Could not resolve argument "Symfony\Config\ApiPlatformConfig $config" for "/config/packages/api_platform.php" in /config/packages/api_platform.php (which is being imported from "/src/Kernel.php")." ?

Could you try removing the cache with `rm -Rf var/cache` to see if it fixes the issue? If not, could you manage to gather a full stack trace (`bin/console cache:clear -vvv` for instance)?

I don't manage to reproduce the issue locally with the 4.0 branch and the `api-platform/symfony` package.

**Comment by stephanvierkant** [comment]
>        "api-platform/symfony": "^4.0",
>        "symfony/config": "^7.1.1",

> $ bin/console cache:clear -vvv

    In FileLoader.php line 178:
    
    [Symfony\Component\Config\Exception\LoaderLoadException]                                                                                                                                                                                                                                                                
    Could not resolve argument "Symfony\Config\ApiPlatformConfig $config" for "{projectDir}/config/packages/api_platform.php" in {projectDir}/config/packages/api_platform.php (which is being imported from "{projectDir}/src/Kernel.php").
    
    
    Exception trace:
    at {projectDir}/vendor/symfony/config/Loader/FileLoader.php:178
    Symfony\Component\Config\Loader\FileLoader->doImport() at {projectDir}/vendor/symfony/config/Loader/FileLoader.php:83
    Symfony\Component\Config\Loader\FileLoader->import() at {projectDir}/vendor/symfony/dependency-injection/Loader/FileLoader.php:78
    Symfony\Component\DependencyInjection\Loader\FileLoader->import() at {projectDir}/vendor/symfony/dependency-injection/Loader/Configurator/ContainerConfigurator.php:71
    Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator->import() at {projectDir}/src/Kernel.php:18
    App\Kernel->configureContainer() at {projectDir}/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:187
    App\Kernel->Symfony\Bundle\FrameworkBundle\Kernel\{closure}() at {projectDir}/vendor/symfony/dependency-injection/Loader/ClosureLoader.php:36
    Symfony\Component\DependencyInjection\Loader\ClosureLoader->load() at {projectDir}/vendor/symfony/config/Loader/DelegatingLoader.php:37
    Symfony\Component\Config\Loader\DelegatingLoader->load() at {projectDir}/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:143
    App\Kernel->registerContainerConfiguration() at {projectDir}/vendor/symfony/http-kernel/Kernel.php:607
    Symfony\Component\HttpKernel\Kernel->buildContainer() at {projectDir}/vendor/symfony/http-kernel/Kernel.php:494
    Symfony\Component\HttpKernel\Kernel->initializeContainer() at {projectDir}/vendor/symfony/http-kernel/Kernel.php:740
    Symfony\Component\HttpKernel\Kernel->preBoot() at {projectDir}/vendor/symfony/http-kernel/Kernel.php:120
    Symfony\Component\HttpKernel\Kernel->boot() at {projectDir}/vendor/symfony/framework-bundle/Console/Application.php:177
    Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at {projectDir}/vendor/symfony/framework-bundle/Console/Application.php:69
    Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at {projectDir}/vendor/symfony/console/Application.php:167
    Symfony\Component\Console\Application->run() at {projectDir}/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
    Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at {projectDir}/vendor/autoload_runtime.php:29
    require_once() at {projectDir}/bin/console:15
    
    In PhpFileLoader.php line 136:
    
    [InvalidArgumentException]                                                                                                                            
    Could not resolve argument "Symfony\Config\ApiPlatformConfig $config" for "{projectDir}/config/packages/api_platform.php".
    
    
    Exception trace:
    at {projectDir}/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php:136
    Symfony\Component\DependencyInjection\Loader\PhpFileLoader->executeCallback() at {projectDir}/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php:64
    Symfony\Component\DependencyInjection\Loader\PhpFileLoader->load() at {projectDir}/vendor/symfony/config/Loader/FileLoader.php:163
    Symfony\Component\Config\Loader\FileLoader->doImport() at {projectDir}/vendor/symfony/config/Loader/FileLoader.php:83
    Symfony\Component\Config\Loader\FileLoader->import() at {projectDir}/vendor/symfony/dependency-injection/Loader/FileLoader.php:78
    Symfony\Component\DependencyInjection\Loader\FileLoader->import() at {projectDir}/vendor/symfony/dependency-injection/Loader/Configurator/ContainerConfigurator.php:71
    Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator->import() at {projectDir}/src/Kernel.php:18
    App\Kernel->configureContainer() at {projectDir}/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:187
    App\Kernel->Symfony\Bundle\FrameworkBundle\Kernel\{closure}() at {projectDir}/vendor/symfony/dependency-injection/Loader/ClosureLoader.php:36
    Symfony\Component\DependencyInjection\Loader\ClosureLoader->load() at {projectDir}/vendor/symfony/config/Loader/DelegatingLoader.php:37
    Symfony\Component\Config\Loader\DelegatingLoader->load() at {projectDir}/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:143
    App\Kernel->registerContainerConfiguration() at {projectDir}/vendor/symfony/http-kernel/Kernel.php:607
    Symfony\Component\HttpKernel\Kernel->buildContainer() at {projectDir}/vendor/symfony/http-kernel/Kernel.php:494
    Symfony\Component\HttpKernel\Kernel->initializeContainer() at {projectDir}/vendor/symfony/http-kernel/Kernel.php:740
    Symfony\Component\HttpKernel\Kernel->preBoot() at {projectDir}/vendor/symfony/http-kernel/Kernel.php:120
    Symfony\Component\HttpKernel\Kernel->boot() at {projectDir}/vendor/symfony/framework-bundle/Console/Application.php:177
    Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at {projectDir}/vendor/symfony/framework-bundle/Console/Application.php:69
    Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at {projectDir}/vendor/symfony/console/Application.php:167
    Symfony\Component\Console\Application->run() at {projectDir}/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
    Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at {projectDir}/vendor/autoload_runtime.php:29
    require_once() at {projectDir}/bin/console:15
    
    In PhpFileLoader.php line 192:
    
    [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                                                                                                                                                                                                                                                                                                       
    There is no extension able to load the configuration for "Symfony\Config\ApiPlatformConfig". Looked for namespace "api_platform", found "async_aws", "doctrine", "doctrine_fixtures", "doctrine_migrations", "snc_redis", "debug", "framework", "mercure", "monolog", "security", "twig", "web_profiler", "webpack_encore", "twig_extra".
    
    
    Exception trace:
    at {projectDir}/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php:192
    Symfony\Component\DependencyInjection\Loader\PhpFileLoader->configBuilder() at {projectDir}/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php:134
    Symfony\Component\DependencyInjection\Loader\PhpFileLoader->executeCallback() at {projectDir}/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php:64
    Symfony\Component\DependencyInjection\Loader\PhpFileLoader->load() at {projectDir}/vendor/symfony/config/Loader/FileLoader.php:163
    Symfony\Component\Config\Loader\FileLoader->doImport() at {projectDir}/vendor/symfony/config/Loader/FileLoader.php:83
    Symfony\Component\Config\Loader\FileLoader->import() at {projectDir}/vendor/symfony/dependency-injection/Loader/FileLoader.php:78
    Symfony\Component\DependencyInjection\Loader\FileLoader->import() at {projectDir}/vendor/symfony/dependency-injection/Loader/Configurator/ContainerConfigurator.php:71
    Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator->import() at {projectDir}/src/Kernel.php:18
    App\Kernel->configureContainer() at {projectDir}/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:187
    App\Kernel->Symfony\Bundle\FrameworkBundle\Kernel\{closure}() at {projectDir}/vendor/symfony/dependency-injection/Loader/ClosureLoader.php:36
    Symfony\Component\DependencyInjection\Loader\ClosureLoader->load() at {projectDir}/vendor/symfony/config/Loader/DelegatingLoader.php:37
    Symfony\Component\Config\Loader\DelegatingLoader->load() at {projectDir}/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:143
    App\Kernel->registerContainerConfiguration() at {projectDir}/vendor/symfony/http-kernel/Kernel.php:607
    Symfony\Component\HttpKernel\Kernel->buildContainer() at {projectDir}/vendor/symfony/http-kernel/Kernel.php:494
    Symfony\Component\HttpKernel\Kernel->initializeContainer() at {projectDir}/vendor/symfony/http-kernel/Kernel.php:740
    Symfony\Component\HttpKernel\Kernel->preBoot() at {projectDir}/vendor/symfony/http-kernel/Kernel.php:120
    Symfony\Component\HttpKernel\Kernel->boot() at {projectDir}/vendor/symfony/framework-bundle/Console/Application.php:177
    Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at {projectDir}/vendor/symfony/framework-bundle/Console/Application.php:69
    Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at {projectDir}/vendor/symfony/console/Application.php:167
    Symfony\Component\Console\Application->run() at {projectDir}/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
    Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at {projectDir}/vendor/autoload_runtime.php:29
    require_once() at {projectDir}/bin/console:15

**Comment by dunglas** [comment]
Ok I just noticed you use PHP config... sorry about that.

But from where `Symfony\Config\ApiPlatformConfig` is coming in the first place? It doesn't seem to be part of API Platform.
Is this provided by a third-party package? Sorry, I'm not familiar at all with PHP config.

**Comment by stephanvierkant** [comment]
Never looked in the internal working, but for most of the libraries I use, PHP config objects are available. And it used to works with API Platform.

(I don't understand why one would still use yaml, I love the php config because of code completion)

**Comment by dunglas** [comment]
I tried on a test project and the PHP config works for me with 4.0 and `api-platform/symfony`.
Could you show me your `config/bundles.php` please?

**Comment by stephanvierkant** [comment]
I'll try to create a reproducer.
