### ISSUE TITLE
Attempted to call an undefined method named "getNativeType" of class "ApiPlatform\Metadata\ApiProperty"

### ISSUE THREAD

**Issue by coissay** [api-platform/core#7404]
**API Platform version(s) affected**: 4.1.24

**Description**  
I am using a custom serializer that implements DenormalizerInterface, NormalizerInterface. in order to add translation when denormalize my json. Then i send it to an `ObjectNormalizer $objectNormalizer`.

Since the update from 4.1.23 to 4.1.24 i got the following error:
`Attempted to call an undefined method named "getNativeType" of class "ApiPlatform\Metadata\ApiProperty".`
in `vendor/api-platform/serializer/AbstractItemNormalizer.php` (line 881)
when `$type = $propertyMetadata->getNativeType();` is called

**How to reproduce**  
update your version and setup a custom normalizer call, the issue come from a method called inside the vendor of ApiPlatform so i guess this should trigger the error

**Possible Solution**  
get the native type by using `getBuiltinType` instead ?

**Additional Context**  
Linked to: https://github.com/api-platform/core/issues/8168
[response.html](https://github.com/user-attachments/files/22508553/response.html)

**Comment by fcharrier** [comment]
Hi,

I have exactly the same problem when I update dependencies of my app.

I had a look at the source code:
- as you noticed, getNativeType is called in api-platform/serializer 4.2.0
- but this method is not available in my version of api-platform/metadata, which is still 4.1.18

I suppose api-platform/serializer 4.2.0 should require api-platform/metadata >= 4.2.0

I tried to force api-platform/metadata 4.2 in my dependencies, but it was not compatible with other constraints.

Finally it works on my app by updating :
- api-platform/metadata to 4.2.0
- symfony/type-info to 7.3 (type-info was not a direct dependency of my app, but adding this requirement force this version and allows the update to metadata 4.2)

I hope it helps


Note: I realize your are updating to 4.1.24, not 4.2. But I think the root cause is the same

**Comment by fcharrier** [comment]
Hello @soyuka 

it seems this commit : https://github.com/api-platform/core/commit/4ce82a1738e6bdab685ed278d6495d68beecfdb6
add the call to getNativeType in Serializer component, without updating dependency.

Is it normal?

Maybe I miss something :)

**Comment by soyuka** [comment]
Indeed I'm surprised our CI didn't catch that, my guess is that we don't test ApiProperty in the serializer unit tests

**Comment by fcharrier** [comment]
I'm just wondering if the dependency update is enough: when we update serializer from 4.1.23 to 4.1.24, it requires metadat 4.2... Ok, but the update of serializer with only a patch change (4.1.23 -> 4.1.24) should contains bug fixes only, not a dependency to a greater version of metadata...

**Comment by vinceAmstoutz** [comment]
@soyuka I think this issue is resolved

**Comment by fcharrier** [comment]
I agree !

**Comment by coissay** [comment]
<img width="1529" height="1137" alt="Image" src="https://github.com/user-attachments/assets/bbe64605-6a39-443b-af8e-aed9f02fe42d" />

It look like to me that the issue is still here with "api-platform/symfony": "^4.1.25"

I just did a composer update, i was still in "api-platform/symfony": "^4.1.23", prior to that in order to avoid the error

**Comment by Lurivar** [comment]
Can confirm that I still get the error too. 4.1.25 is the last working version for me. 
Anything beyond ( and including ) 4.2.0 gets me the error.

**Comment by botjaeger** [comment]
Just got the same error on my end, any updates on this?

**Comment by lolop93** [comment]
same here, error already existe

**Comment by MonaGolkarAtGitHub** [comment]
Yup, we got it too. Downgrading seem to work. Waiting for any sign of life here

**Comment by timble-one** [comment]
I needet to fix: `"api-platform/serializer": "4.1.25"`

**Comment by soyuka** [comment]
https://github.com/api-platform/core/blob/4.1/src/Serializer/AbstractItemNormalizer.php 

4.1 does not have any getNativeType it must be that another dependency is at 4.2, please make sure to install `4.1.*` on all your components especially: 

- api-platform/serializer
- api-platform/metadata

**Comment by coissay** [comment]
@soyuka the thing is that this does not work

[composer.json](https://github.com/user-attachments/files/23266363/composer.json)

in my composer.lock i have

```      
"require": {
        "api-platform/documentation": "^4.1.11",
        "api-platform/json-schema": "^4.1.11",
        "api-platform/jsonld": "^4.1.11",
        "api-platform/metadata": "^4.1.11",
        "api-platform/serializer": "^4.1.11",
        "api-platform/state": "^4.1.11",
        "php": ">=8.2",
        "symfony/web-link": "^6.4 || ^7.1"
      },
```
there is never 4.2 reference 

The only place there is a 4.2.0 is in the `support/source` section

```
      "support": {
        "source": "https://github.com/api-platform/serializer/tree/v4.2.0"
      },
```

Even if i change it to 

```
      "support": {
        "source": "https://github.com/api-platform/serializer/tree/v4.1.26"
      },
```

there is still the same error

<img width="1524" height="1134" alt="Image" src="https://github.com/user-attachments/assets/f07c45d9-1d9f-4be9-a350-ad7fe5285347" />



Edit: by adding a composer require with the 2 package specificly it is ok (i don't get why it did not work before since the lock said i was at the right version already)

Use:
```
composer require api-platform/serializer:4.1.26
composer require api-platform/metadata:4.1
```

I close the issue since this fix the problem

**Comment by soyuka** [comment]
Use this constraint instead: `~4.1.11`
