### ISSUE TITLE
Add jsonld context to resource

### ISSUE THREAD

**Issue by maechler** [api-platform/core#767]
It would be nice to have the possibility to split the property context into the namespace and the property itself. Here an example to illustrate what I mean:

**Entity BibliographicResource**
```php
class BibliographicResource
{
    /**
     * @var string
     *
     * @ApiProperty(iri="http://purl.org/dc/terms/title")
     */
    private $title;
}
```

**Current output**
Context:

```json
{
    "title": "http://purl.org/dc/terms/title"
}
```

Entity:

```json
{
      "title": "some title"
}
```

**Desired output**

Context:

```json
{
    "dct": "http://purl.org/dc/terms/"
}
```

Entity:

```json
{
      "dct:title": "some title"
}
```

**Possible implementation**

One way of implementing this could probably be to add context definitions to the entity class. 
e.g.

```php

/**
 * @ApiResource(
 *     "jsonld_context"={
 *         "context": {
 *             "dct":"http://purl.org/dc/terms/"
 *         }       
 *     }
 * )
 */
class BibliographicResource
{
    /**
     * @var string
     *
     * @ApiProperty(iri="dct:title")
     */
    private $title;
}
```

**Comment by Simperfit** [comment]
@maechler This is fixed ?

**Comment by maechler** [comment]
@Simperfit No, that is not fixed yet. I have added support to extend the json-ld context on property level: https://github.com/api-platform/core/pull/752
But to allow to modify the context completely, it should also be possible on an entity level.
